# Generated by Django 3.2.9 on 2021-11-05 15:43

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayLoadLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('process_id', models.CharField(max_length=255)),
                ('bmi_object', jsonfield.fields.JSONField()),
                ('time_stamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('request_id', models.CharField(db_index=True, max_length=255)),
                ('bmi_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('weight', models.DecimalField(db_index=True, decimal_places=5, max_digits=13)),
                ('height', models.DecimalField(db_index=True, decimal_places=5, max_digits=13)),
                ('gender', models.CharField(db_index=True, max_length=255)),
                ('advisor_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('requested_ip', models.CharField(db_index=True, max_length=255)),
            ],
        ),
    ]
