# Generated by Django 3.2.9 on 2021-11-05 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vm_bm', '0001_initial'),
    ]

    operations = [
    ]
