# Generated by Django 3.2.9 on 2021-11-05 17:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vm_bm', '0002_auto_20211105_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payloadlog',
            name='height',
        ),
        migrations.RemoveField(
            model_name='payloadlog',
            name='weight',
        ),
        migrations.AddField(
            model_name='payloadlog',
            name='bmi_category',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payloadlog',
            name='health_risk',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
